---
default: true

# config: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD007/ul-indent - Unordered list indentation
MD007:
  # Spaces for indent
  # indent: 2
  indent: 4
  # Whether to indent the first level of the list
  start_indented: false
  # Spaces for first level indent (when start_indented is set)
  start_indent: 2

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 240
  # Number of characters for headings
  heading_line_length: 240
  # Number of characters for code blocks
  code_block_line_length: 240
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Include headings
  headers: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  allow_different_nesting: false
  # Only check sibling headings
  siblings_only: true
