---
# https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/texthooks
    rev: 0.4.0
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.20.0
    hooks:
      - id: check-github-workflows
      - id: check-renovate
  # needs configuration
  # - repo: https://github.com/jguttman94/pre-commit-gradle
  #   rev: v0.3.0
  #   hooks:
  #     - id: gradle-check
  #     - id: gradle-build
  #     - id: gradle-spotless
