name: Renovate
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_5_*_*_1 # At 05:00 on Monday.
    - cron: '0 5 * * 1'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.106.0
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # LOG_LEVEL: 'debug'
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
